#!/usr/bin/env ruby

git_bundles = [
  'git://github.com/tpope/vim-cucumber.git',
  'git://github.com/tpope/vim-fugitive.git',
  'git://github.com/tpope/vim-git.git',
  'git://github.com/tpope/vim-haml.git',
  'git://github.com/tpope/vim-markdown.git',
  'git://github.com/tpope/vim-rails.git',
  'git://github.com/tpope/vim-repeat.git',
  'git://github.com/tpope/vim-surround.git',
  'git://github.com/tpope/vim-vividchalk.git',
  'git://github.com/tpope/vim-endwise.git',
  'git://github.com/tpope/vim-jdaddy.git',
  'git://github.com/ervandew/supertab.git',
  'git://github.com/vim-ruby/vim-ruby.git',
  'git://github.com/vim-syntastic/syntastic.git'
]

vim_org_scripts = [
#  ['IndexedSearch', '7062',  'plugin'],
#  ['jquery',        '15752', 'syntax'],
#  # ['autoclose',     '10873', 'plugin'],
#  ['repeat',        '8206',  'plugin'],
#  ['Rename',        '16331',  'plugin'],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), 'bundle')

FileUtils.cd(bundles_dir)

puts 'Trashing everything (lookout!)'
Dir['*'].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
